apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
      - image: aldoleandro/cursosarm64:v1
        name: cursosarm64
        ports:
          - containerPort: 8002
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos-config
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos-config
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos-config
                key: database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: msvc-cursos-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-cursos-secret
                key: password
          - name: USUARIOS_URL
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos-config
                key: usuario_url
