apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
      - image: aldoleandro/cursosarm64:v1
        name: cursosarm64
        ports:
          - containerPort: 8002
        env:
          - name: PORT
            value: "8002"
          - name: DB_HOST
            value: "postgres16:5432"
          - name: DB_DATABASE
            value: "msvc_cursos"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "asaavedm"
          - name: USUARIOS_URL
            value: "msvc-usuarios:8001"
