version: "3.9" # Version de docker-compose
services:
  mysql:
    container_name: mysql8
    image: mysql:8.0-oraclelinux8
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=asaavedm
      - MYSQL_DATABASE=msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres16:
    container_name: postgres16
    image: postgres:16-alpine
    ports:
      - "5632:5432"
    environment:
      - POSTGRES_PASSWORD=asaavedm
      - POSTGRES_DB=msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: aldoleandro/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql
    restart: always

  msvc-cursos:
    container_name: msvc-cursos
    image: aldoleandro/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres16
      - msvc-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
    external: true
  data-postgres:
    name: data-postgres
    external: true
networks:
  spring:
